server:
  port: 8084

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3310}/${MYSQL_DB:booking_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

integration:
  flight-service-base-url: ${FLIGHT_SERVICE_BASE_URL:http://api-gateway:8080}
  seat-service-base-url: ${SEAT_SERVICE_BASE_URL:http://api-gateway:8080}
  payment-service-base-url: ${PAYMENT_SERVICE_BASE_URL:http://api-gateway:8080}
  payment-enabled: ${PAYMENT_INTEGRATION_ENABLED:false}

booking:
  default-tax-rate: 0.18
  meal-fee: 350
  luggage-fee-per-kg: 120
  event-exchange: ${BOOKING_EVENT_EXCHANGE:skybooker.events}

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info
