sonar.projectKey=SkyBooker
sonar.projectName=SkyBooker
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend
sonar.tests=backend,frontend/src
sonar.test.inclusions=backend/**/src/test/**,frontend/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/*.spec.ts

sonar.java.binaries=backend/**/target/classes

sonar.coverage.jacoco.xmlReportPaths=backend/**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=backend/**/dto/**,backend/**/entity/**,backend/**/*Application.java,frontend/src/app/app.component.ts,frontend/src/app/core/models/**
