server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:auth_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: ${JWT_SECRET:U2t5Qm9va2VySnd0U2VjcmV0S2V5U2t5Qm9va2VySnd0U2VjcmV0S2V5MTIzNDU2Nzg5MA==}
  expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.skybooker.authservice: INFO
